SRCSDIR=../repo/
SRCS=get_next_line.c get_next_line_utils.c 
SRCSBONUS=get_next_line_bonus.c get_next_line_utils.c
HEADERS=get_next_line.h
SRCSFP=$(SRCS:%=$(SRCSDIR)%)
SRCSBONUSFP=$(SRCSBONUS:%=$(SRCSDIR)%)
CFLAGS=-Wall -Wextra -Werror

all:
	./test.sh
FORCE :
